openshift/multus-cni

- types/conf.go
This patch fixes the issue described in #289 where deviceID for
delegate plugin was not adding properly if the plugin conf inside
NetConfList.
Change-Id: I1d221f6b0e60a5b888b8e823611dfe12635e6897
Signed-off-by: Abdul Halim <abdul.halim@intel.com>
> fix missing deviceID in NetConfList

- build
Fixes break where libcrypto is being referenced:
> erroring out with: `/var/lib/cni/bin/multus: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory` apparently the last working build was `4.0.0-0.nightly-2019-04-10-182914`
> add CGO_ENABLED=0 to build

- doc/how-to-use.md
- images/entrypoint.sh
- multus/multus.go
Hi
I need to backport `--cni-version` argument in the `entrypoint.sh` as to be able to apply the backport fix [Cluster network operator 293](https://github.com/openshift/cluster-network-operator/pull/293) on release-4.1. Multus supports reading `cniVersion` in its config file, so the only thing missing in 4.1 should be this argument backport in `entrypoint.sh`
I cherry-picked @s1061123 [development](https://github.com/openshift/multus-cni/commit/a4dbe7b102f254db0bf3c18495139ce0762cfe38) from master for this, so I will thus directly assign to him.
/assign @s1061123
> Bug 1743587: Backporting "cni-version" in entrypoint.sh

- doc/how-to-use.md
- images/entrypoint.sh
- images/multus-daemonset-crio.yml
This add logic to restart CRIO once and only once when the Multus configuration is generated. This limits the impact of the CRIO restart, instead of having it restart every time the configuration is generated.
Additionally, this also folds in the upstream requirement to have the source configuration renamed, but, only in the case where we're using the watch loop (to use the original source configuration as a semaphore for network readiness). This rename cannot happen in that case (causes an infinite loop), but, is necessary when you're not using that functionality.
> Bug 1732598: Adds one-shot CRIO restart

- doc/how-to-use.md
- images/entrypoint.sh
Adds option to skip having the entrypoint copy the Multus binary.
Used as:
```
--skip-multus-binary-copy=true
```
> Bug 1725832: Skips binary copy in entrypoint with new parameter

- Dockerfile.openshift
Images in CI apparently mismatch what's used by the build system. Which were failing with a missing git a la:
```
--------------------------------------------------------------------------
The following logs are just the container build portion of the OSBS build:
--------------------------------------------------------------------------
imagebuilder build has begun; waiting for it to finish
--> FROM sha256:8afaf1806c79d7eb8c0ba75b9b141440b0d3137b9570e0fc4e9d696bbbfeed9f as rhel8
--> ADD atomic-reactor-repos/* '/etc/yum.repos.d/'
--> USER root
--> RUN mv -f /etc/yum.repos.d/ubi.repo /tmp || :
--> USER 0
--> ENV SOURCE_GIT_COMMIT=dc0b5c2a93d64fd75407beeb9fa5837bdf4ee2ce SOURCE_DATE_EPOCH=1573148656 BUILD_VERSION=v4.3.0 SOURCE_GIT_URL=https://github.com/openshift/multus-cni …
```
> Installs git via yum for ART builds

- doc/how-to-use.md
- images/entrypoint.sh
- multus/multus.go
In attempt to help cure some ills of upgrades.
Upstream PR @ https://github.com/intel/multus-cni/pull/443
> Exposes readinessindicatorfile and uses wait.PollImmediate

- doc/how-to-use.md
- images/entrypoint.sh
- multus/multus.go
Additionally picks a commit for checking for presence of the use of the readinessindicator file.
> Bug 1805444: Exposes readinessindicatorfile and uses wait.PollImmediate [backport 4.3]

- images/entrypoint.sh
Experimental commit, do not merge. Hacks in method for not removing config invalidation.
> Removes configuration invalidation

- multus/multus.go
This adds the readiness check on CNI DEL. 
This is a WIP until I can have some maintainers discussion about it, as well.
> Adds readinessindicatorfile check on CNI DEL

- k8sclient/k8sclient.go
- k8sclient/k8sclient_test.go
- multus/multus.go
- multus/multus_test.go
- testing/testing.go
- types/conf.go
- types/conf_test.go
- types/types.go
This change adds pod UID and net-attach-def name in verbose log
and sends kubernetes event when net-attach-def is not found.
> Bug 1835033: Logging improvement (UID, net-attach-def) / Backport to 4.4

- multus/multus.go
Otherwise, this can cause a pod to not be fully deleted, its sandbox may remain as the DEL continues to be retried due to exiting non-zero every time.
> Bug 1900835: Multus should exit zero on DEL when cache file is missing and pod cannot be found.

- multus/multus.go
Otherwise, this can cause a pod to not be fully deleted, its sandbox may remain as the DEL continues to be retried due to exiting non-zero every time.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1900835
> Bug 1905230: Multus should exit zero on DEL when cache file is missing [backport 4.6]

- types/conf.go
- types/conf_test.go
When we call mergeRuntimeConfig, the global RuntimeConfig gets
overwritten with the result of the merging, thus affecting the
subsequent delegates.
Do not modify the global RuntimeConfig and instead make a copy
when merging it.
Also, if a value has been provided for CNIDeviceInfoFile in the
delegate's runtimeconfig, overwrite it to avoid possible name
colissions.
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
> Bug 1927896: make a copy of global RuntimeConfig on merge

- pkg/kubeletclient/kubeletclient.go
Signed-off-by: Peng Liu <pliu@redhat.com>
> Bug 1968625: Use the default socket path in GetResourceClient when unspecified

- pkg/k8sclient/k8sclient.go
- pkg/k8sclient/k8sclient_test.go
- pkg/multus/multus.go
- pkg/multus/multus_test.go
- pkg/types/conf.go
- pkg/types/types.go
add handling of pod UIDs passed from runtime from: https://github.com/k8snetworkplumbingwg/multus-cni/pull/742
Additionally picks commits for pollinternval as constants, and pod retries on multiple error types commits for mergeability/conflicts.
> Bug 2017881: add handling of pod UIDs passed from runtime

- deployments/multus-daemonset-crio.yml
to prevent "unknown FS magic on "/var/run/netns/*": 1021994" errors
see https://github.com/containernetworking/plugins/issues/69 and https://github.com/openshift/cluster-network-operator/pull/669
related to https://bugzilla.redhat.com/show_bug.cgi?id=2057618
Signed-off-by: Peter Hunt <pehunt@redhat.com>
> crio: mount /run rslave

- pkg/multus/multus.go
In cmdDel, CNI Spec mentioned that plugin should proceed cmdDel
without any error, hence the change removes error returning
at cmdDel.
> Bug 2071799: Remove error handling for getPod to force to proceed cmdDel.

- pkg/types/conf.go
- pkg/types/conf_test.go
* types: fix usage of strings.Split() for parsing CNI_ARGS
strings.Split() returns a slice, in this case with two elements of
the key and value. As such we shouldn't range over the slice when
the code is expecting a 2-element slice of key/value.
Otherwise we get errors for valid CNI_ARGS like:
2022-04-22T11:53:54Z [error] CreateCNIRuntimeConf: CNI_ARGS K8S_POD_NAMESPACE=openshift-etcd K8S_POD_NAMESPACE 17 is not recognized as CNI arg, skipped
2022-04-22T11:53:54Z [error] CreateCNIRuntimeConf: CNI_ARGS K8S_POD_NAMESPACE=openshift-etcd openshift-etcd 14 is not recognized as CNI arg, skipped
Fixes: d7d2a99ab5b8 ("Replace setenv with runtimeConfig set")
Signed-off-by: Dan Williams <dcbw@redhat.com>
* types/conf: fix handling of CNI_ARGS additions to rt.Args
We want to set the CNI_ARGS value …
> types: fix usage of strings.Split() for parsing CNI_ARGS (#836)

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
- vendor/modules.txt
This accounts for CNI v1.0 formatted IP address information (no longer requires version field)
> Bug 2082360: Bumps net-attach-def client library (for CNI v1.0 IP compatibility)

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
- vendor/modules.txt
This accounts for CNI v1.0 formatted IP address information (no longer requires version field)
> Bug 2084289: Bumps net-attach-def client library (for CNI v1.0 IP compatibility) [backport 4.10]

- pkg/multus/multus.go
This change skips to update pod's network-status annotation
when getPod is failed at the beginning of CmdDel. If getPod is
failed, K8s api gets stucked in many cases, hence pod update
might be failed in most cases.
> Bug 2071799: Skip status update in CmdDel if getPod is failed

- pkg/multus/multus.go
only warn when netns can't be opened
Co-authored-by: dougbtv <dosmith@redhat.com>
> OCPBUGS-8672: SNO: Pods fail to delete, Multus: failed to open netns [backport 4.10]

- pkg/multus/multus.go
In cmdDel, CNI Spec mentioned that plugin should proceed cmdDel
without any error, hence the change removes error returning
at cmdDel.
fix #822
> OCPBUGS-9343: Remove error handling for getPod to force to proceed cmdDel [backport 4.9]

- pkg/multus/multus.go
- pkg/multus/multus_cni020_test.go
- pkg/multus/multus_cni040_test.go
- pkg/multus/multus_cni100_test.go
This change fixes multus to support CNI plugin which does not create any interface and return empty result. Some CNI plugin may do network configuration change only and does not create any interface and return empty CNI result. Current multus assumes that CNI config always creates some interfaces hence above CNI plugin is out of assumption and multus may not work with such plugins.
> OCPBUGS-13815: Fix multus to support CNI plugin which does not create interface

- pkg/multus/multus.go
- pkg/multus/multus_cni020_test.go
- pkg/multus/multus_cni040_test.go
- pkg/multus/multus_cni100_test.go
This change fixes multus to support CNI plugin which does not create any interface and return empty result. Some CNI plugin may do network configuration change only and does not create any interface and return empty CNI result. Current multus assumes that CNI config always creates some interfaces hence above CNI plugin is out of assumption and multus may not work with such plugins.
> OCPBUGS-13814: Fix multus to support CNI plugin which does not create interface [backport 4.13]

- pkg/multus/multus.go
- pkg/multus/multus_test.go
This change fixes multus to support CNI plugin which does not create any interface and return empty result. Some CNI plugin may do network configuration change only and does not create any interface and return empty CNI result. Current multus assumes that CNI config always creates some interfaces hence above CNI plugin is out of assumption and multus may not work with such plugins.
> OCPBUGS-7844: Fix multus to support CNI plugin which does not create interface [backport 4.12]

- images/entrypoint.sh
This re-implements the rotation (which is a downstream carry)
> OCPBUGS-8398: Multus entrypoint should regenerate kubeconfig if secret changes [backport 4.13]

- Dockerfile.openshift
- images/Dockerfile.openshift
Now that the binary is being dynamically compiled downstream, the binary must match the RHEL version of RHCOS because it is copied to the host.
> Add rhel9 binary for multus

- deployments/multus-daemonset-thick.yml
- pkg/k8sclient/k8sclient.go
- pkg/server/exec_chroot.go
- pkg/server/exec_chroot_test.go
- pkg/server/server.go
- pkg/types/conf.go
We used to run chroot in multus main process when calling other CNI plugin binary. We also use a mutex to lock the access to pod files. But this causes performance issues when facing heavy CNI_ADD/CNI_DEL requests.
With this patch, we do chroot in the child processes instead. So file operations in the main process will not be affected by chroot.
This change requires the multus thick plugin pod to mount CNI bin directory to the same path in the container host.
> OCPBUGS-18995: Move chroot from multus main process to its child processes (#1161)

- deployments/multus-daemonset-thick.yml
- pkg/k8sclient/k8sclient.go
- pkg/server/exec_chroot.go
- pkg/server/exec_chroot_test.go
- pkg/server/server.go
- pkg/types/conf.go
We used to run chroot in multus main process when calling other CNI plugin binary. We also use a mutex to lock the access to pod files. But this causes performance issues when facing heavy CNI_ADD/CNI_DEL requests.
With this patch, we do chroot in the child processes instead. So file operations in the main process will not be affected by chroot.
This change requires the multus thick plugin pod to mount CNI bin directory to the same path in the container host.
> OCPBUGS-19679: Move chroot from multus main process to its child processes

- cmd/kubeconfig_generator/main.go
- pkg/k8sclient/kubeconfig.go
- pkg/server/server.go
- pkg/server/types.go
This change introduces certDuration as parameter to customize cert duration. In addition, environment variable for node name is matched to other usages.
> OCPBUGS-19859: Multus annotation permissions: Certificate duration should be configurable

- cmd/kubeconfig_generator/main.go
- pkg/k8sclient/kubeconfig.go
- pkg/server/server.go
- pkg/server/types.go
This change introduces certDuration as parameter to customize cert duration. In addition, environment variable for node name is matched to other usages.
> OCPBUGS-19860: Multus annotation permissions: Certificate duration should be configurable [backport 4.14]

- pkg/types/conf.go
- pkg/types/conf_test.go
when the configuration specifies both an IPv4 and IPv6 default route, the IsFilterV4Gateway and IsFilterV6Gateway flags should both be false, to allow the gateway configuration.
The logic in CheckGatewayConfig would do the inverse, setting both to true in case of both IPv4 and IPv6 gateway.
Fixes: d52f2b6a ("Update libcni cache when default-route net selection is used")
> OCPBUGS-22461: fix multiple default gw

- cmd/cert-approver/main.go
- cmd/multus-daemon/main.go
- cmd/thin_entrypoint/main_test.go
- pkg/server/api/api.go
- pkg/server/api/shim.go
- pkg/server/config/config_suite_test.go
- pkg/server/config/generator_test.go
- pkg/server/config/manager_test.go
Reverts #205 ; tracked by https://issues.redhat.com/browse/OCPBUGS-26397
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Multiple payload failures due to multus-cni CmdAdd timeouts for SND
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-sdn-upgrade
```
CC: @dougbtv
<div align="right">
PR created by <a …
> OCPBUGS-26397: Revert #205 "Adds a wait on unix socket readiness"

- cmd/cert-approver/main.go
- cmd/multus-daemon/main.go
- cmd/thin_entrypoint/main_test.go
- pkg/server/api/api.go
- pkg/server/api/shim.go
- pkg/server/config/config_suite_test.go
- pkg/server/config/generator_test.go
- pkg/server/config/manager_test.go
Reverts #206 ; tracked by OCPBUGS-26535
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Multiple payload failures due to multus-cni CmdAdd timeouts for SND
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-sdn-upgrade
```
CC: @dougbtv
<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></ …
> OCPBUGS-26535: Revert #206 "Adds a wait on unix socket readiness [backport 4.15]"

- pkg/k8sclient/kubeconfig.go
When user recreate whole cluster certs, multus thick plugin's previous cert is no longer valid. In such case, we need to prevent to use cert manager's old certs and restart it from bootstrap kubeconfig. This fix reloads client config from bootstrap kubeconfig if cert mgr's cert is failed to load pod.
> OCPBUGS-27429: Reload bootstrap kubeconfig if cert mgr failed to load valid certs

- pkg/netutils/netutils.go
- pkg/netutils/netutils_test.go
deleteDefaultGWResult() may create 'routes:null' in CNI cache file and it causes nil pointer access at addDefaultGWCacheBytes(). This code change prevents deleteDefaultGWResult() to generate 'routes:null' in cache file.
> OCPBUGS-33256: Fix CNI cache update function to prevent nil access

- pkg/netutils/netutils.go
- pkg/netutils/netutils_test.go
deleteDefaultGWResult() may create 'routes:null' in CNI cache file and it causes nil pointer access at addDefaultGWCacheBytes(). This code change prevents deleteDefaultGWResult() to generate 'routes:null' in cache file.
> OCPBUGS-33477: Fix CNI cache update function to prevent nil access

- pkg/netutils/netutils.go
- pkg/netutils/netutils_test.go
deleteDefaultGWResult() may create 'routes:null' in CNI cache file and it causes nil pointer access at addDefaultGWCacheBytes(). This code change prevents deleteDefaultGWResult() to generate 'routes:null' in cache file.
> OCPBUGS-33478: Fix CNI cache update function to prevent nil access

- pkg/server/api/api.go
- pkg/server/api/shim.go
This modifies the behavior on CNI DEL for the thick plugin to just check once for API readiness, as opposed to waiting.
(cherry picked from commit 181f56f026078cb58871d7fe3002ffadde8c256c)
> OCPBUGS-33559: Thick plugin should not wait for API readiness on CNI DEL

- Dockerfile.microshift
- Dockerfile.openshift
Similar to openshift/egress-router-cni#82. Needed for OKD installs to succeed. https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-okd-scos-4.16-e2e-aws-ovn/1798613975458385920/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods.json shows the failing containers with this error.
> OKD-218: install util-linux

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
- vendor/modules.txt
This fixes the default:true for multiple interface returns from CNI for cluster default network, where all interfaces in that return were marked as default:true in the network-status
> OCPBUGS-41875: Bumps net-attach-def client library to v1.7.2

- cmd/multus-daemon/main.go
- deployments/multus-daemonset-crio.yml
- deployments/multus-daemonset-thick.yml
- deployments/multus-daemonset.yml
- pkg/server/api/api.go
- pkg/server/server.go
- pkg/server/thick_cni_test.go
This PR introduces graceful shutdown functionality to the Multus daemon by adding a `/readyz` endpoint alongside the existing `/healthz`. The /readyz endpoint starts returning 500 once a SIGTERM is received, indicating the daemon is in shutdown mode. During this time, CNI requests can still be processed for a short window. The daemonset configs have been updated to increase `terminationGracePeriodSeconds` from 10 to 30 seconds, ensuring we have a bit more time for these clean shutdowns.
This addresses a race condition during pod transitions where the readiness check might return true, but a subsequent CNI request could fail if the daemon shuts down too quickly. By introducing the /readyz endpoint and delaying the shutdown, we can handle ongoing CNI requests more gracefully, reducing the …
> OCPBUGS-42236: (CARRY) Graceful shutdown functionality for multus daemon

- go.mod
- go.sum
- vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
- vendor/modules.txt
From the release notes:
> This release contains a fix related to the determination of the default interface, e.g. setting the default parameter to true in the network-status annotation based on the presence of a gateway in the CNI ADD success result ips.gateway and makes the determination of the default based on the first interface that has an associated value of gateway (using the interface index in the ips element in the CNI ADD success result).
> This provides flexibility especially in CRI-O which uses the first interface and IP addresses for the pod.IP in Kubernetes, therefore. Containerd functionality is unchanged in that it uses the value for the IP addresses specifically
> It's worth noting that CNI ADD success results which do not contain any interfaces will be discarded in this …
> OCPBUGS-43390: Update net-attach-def client library to 1.7.5 for cri-o functionality

- pkg/k8sclient/k8sclient.go
- pkg/multus/multus.go
Reverts carry 713f28b51aeda2d3278c24062c5b7619bc1c8a63
Brings in changes from:
context for getpod: https://github.com/k8snetworkplumbingwg/multus-cni/pull/1372/commits
and getlivepod to avoid cache misses (to patch carry with upstream): https://github.com/k8snetworkplumbingwg/multus-cni/pull/1332/files
> OCPBUGS-45037: Bring in getpodcontext (fix cache miss carry)

- pkg/multus/multus.go
This change adds toleration for such errors like:
```
failed to [query/update] the pod pod-name-here in out of cluster comm: pod "pod-name-here" not found
```
During CNI ADD. ~While this change is a trade off in terms of debugability for RBAC, it's potentially noisy in scaled clusters when it is working properly.~
(edit: that's not the case anymore after I updated my code)
> OCPBUGS-53087: Tolerate issues writing network status annotation on CNI ADD
