openshift/multus-cni

images/entrypoint.sh
k8sclient/k8sclient.go
k8sclient/k8sclient_test.go
logging/logging.go
logging/logging_test.go
multus/multus.go

Includes these upstream PRs:
* https://github.com/intel/multus-cni/pull/271
* https://github.com/intel/multus-cni/pull/273
* https://github.com/intel/multus-cni/pull/275
* https://github.com/intel/multus-cni/pull/280

Release v3 updates

---

doc/how-to-use.md
images/entrypoint.sh
images/multus-daemonset-crio.yml
types/conf.go

Originates from release-v3 branch upstream. Winds up picking up a minor commit from Zenghui from late May, as well.

Bug 1732598: Entrypoint changes for watch loop & CRIO restart

---

doc/configuration.md
doc/how-to-use.md
images/entrypoint.sh
multus/multus.go

Includes commits for:
* `binDir` fix (using `CNI_PATH`)
* Entrypoint parameter to expose `binDir` configuration.

Bug 1752453: Adds additional bin dir functionality

---

build

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@squeed @dougbtv PTAL.
I guess there'll be another PR for multiple userspace rhel once the images are ready.

RE: #1725832 - openssl support, dynamically link glibc

---

Dockerfile.openshift

Dockerfile template from Doug Smith <dosmith@redhat.com>
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@dougbtv @mrunalp PTAL

build for rhel7 and rhel8 userspaces

---

Dockerfile.openshift

to avoid using git in build process

sets a VERSION environment variable for RHEL8

---

doc/how-to-use.md
images/entrypoint.sh
multus/multus.go

Bug 1805774: Exposes readinessindicatorfile and uses wait.PollImmediate [backport 4.4]

---

images/entrypoint.sh

Bug 1809285: Removes configuration invalidation [4.4 backport]

---

images/entrypoint.sh

Bug 1809283: Removes configuration invalidation [4.3 backport]

---

multus/multus.go

Bug 1824940: Adds readinessindicatorfile check on CNI DEL

---

.github/workflows/kind-e2e.yml
e2e/simple-pod.yml
e2e/test-simple-pod.sh
pkg/k8sclient/k8sclient.go

Discovered upstream in https://github.com/k8snetworkplumbingwg/multus-cni/issues/642

Change nil instead of error in case of no network annotation

---

OWNERS

Added reviewer nicklesimba to OWNERS

Added reviewer nicklesimba

---

images/entrypoint.sh

For hourly rotating svc account tokens

Bug 1973423: Updates entrypoint to rebuild kubeconfig when service account token or ca changes

---

images/entrypoint.sh

For hourly rotating svc account tokens

Bug 1972167: Updates entrypoint to rebuild kubeconfig when service account token or ca changes

---

.github/workflows/legacy-kind-e2e.yml
cmd/controller/main.go
deployments/multus-daemonset-crio.yml
deployments/multus-daemonset-gke-1.16.yml
deployments/multus-daemonset-thick-plugin.yml
deployments/multus-daemonset.yml
docs/development.md
docs/quickstart.md
e2e/legacy-multus-daemonset.yml
e2e/multus-daemonset.yml
e2e/setup_cluster.sh
go.mod
images/README.md
images/entrypoint.sh
pkg/config/generator.go
pkg/config/generator_test.go
pkg/config/manager.go
pkg/config/manager_test.go
pkg/k8sclient/k8sclient.go
pkg/multus/multus.go
pkg/multus/multus_test.go
pkg/netutils/netutils.go
pkg/netutils/netutils_test.go
pkg/types/conf.go
pkg/types/conf_test.go
pkg/types/types.go
vendor/modules.txt

Fixes BZ [2038019](https://bugzilla.redhat.com/show_bug.cgi?id=2038019). But, we also need an upstream sync, so... two birds with one stone.

Bug 2038019: Upstream sync for 4.11

---

images/entrypoint.sh

This re-implements the rotation (which is a downstream carry)

Multus entrypoint should regenerate kubeconfig if secret changes

---

.snyk
cmd/kubeconfig_generator/main.go
cmd/multus-daemon/main.go
pkg/server/config/manager.go

This commit makes .synk file to exclude directories that needs to be ignored.

OCPBUGS-28271: Fix SAST scan issues for multus-cni-container [4.15]

---

.snyk
cmd/kubeconfig_generator/main.go
cmd/multus-daemon/main.go
pkg/server/config/manager.go

This commit makes .synk file to exclude directories that needs to be ignored.

 OCPBUGS-26331: Fix SAST scan issues for multus-cni-container [4.14]

---

OWNERS

removes members that have left the org/team and adds myself and peng
@dougbtv @zshi-redhat

OCPBUGS-34911: Update owners file

---

pkg/multus/multus.go

For a previous fix of returning an empty CNI result when pods are not found, the CNI result wasn't properly structured. This fixes the structuring.

TRT-2057: Properly structure empty CNI result
